remote_theme: "godalming123/matirlize-jekyll-theme"

#url: https://godalming123.github.io/blog
baseurl: "/blog"

collections:
  potentially_coming_soon:
    output: false
    sort_by: date
    name: Potentially Coming Soon
    description: The latest things that could be in the pipeline
    icon: ""
    isPostType: true
    #iconAlt: a suitcase
  still_in_the_writing:
    output: true
    sort_by: date
    name: Still In The Writing
    description: See the future of this blog. but be warned; Its wacky!
    icon: ""
    isPostType: true
    #iconAlt: a suitcase
  working_on:
    output: true
    sort_by: date
    name: What I'm Working On
    description: The latest things I'm working on
    icon: /icons/suitcase.svg
    isPostType: true
    iconAlt: a suitcase
  tuturiols:
    output: true
    sort_by: date
    name: My Tuturiols
    description: Browse all of my tuturiols
    icon: ""
    isPostType: true
    #iconAlt: a tuturiol
  blogs:
    output: true
    sort_by: date
    name: My Blogs
    description: The latest happening's
    icon: /icons/blogger.svg
    iconAlt: a capital B
    isPostType: true

collections_dir: my_collections
accent-color: 26a69a #hex color value
faded-accent-color: 1d8c81 #hex color value this is used for background when app is launching